/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { FeedItem } from '../models';

export interface RetrieveFeedItemRequest {
  id: string;
}

/**
 *
 */
export class FeedItemsApi extends runtime.BaseAPI {
  /**
   * This viewset automatically provides `list`, `retrieve` actions.
   */
  async listFeedItemsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FeedItem>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/feed-items/`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * This viewset automatically provides `list`, `retrieve` actions.
   */
  async listFeedItems(initOverrides?: RequestInit): Promise<Array<FeedItem>> {
    const response = await this.listFeedItemsRaw(initOverrides);
    return await response.value();
  }

  /**
   * This viewset automatically provides `list`, `retrieve` actions.
   */
  async retrieveFeedItemRaw(
    requestParameters: RetrieveFeedItemRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<FeedItem>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling retrieveFeedItem.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/feed-items/{id}/`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * This viewset automatically provides `list`, `retrieve` actions.
   */
  async retrieveFeedItem(id: string, initOverrides?: RequestInit): Promise<FeedItem> {
    const response = await this.retrieveFeedItemRaw({ id: id }, initOverrides);
    return await response.value();
  }
}
