/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AidCentersApi", () => {
  let instance: api.AidCentersApi
  beforeEach(function() {
    instance = new api.AidCentersApi(config)
  });

  test("createAidCenter", () => {
    const body: api.AidCenter = undefined
    return expect(instance.createAidCenter(body, {})).resolves.toBe(null)
  })
  test("destroyAidCenter", () => {
    const slug: string = "slug_example"
    return expect(instance.destroyAidCenter(slug, {})).resolves.toBe(null)
  })
  test("listAidCenters", () => {
    return expect(instance.listAidCenters({})).resolves.toBe(null)
  })
  test("partialUpdateAidCenter", () => {
    const slug: string = "slug_example"
    const body: api.AidCenter = undefined
    return expect(instance.partialUpdateAidCenter(slug, body, {})).resolves.toBe(null)
  })
  test("retrieveAidCenter", () => {
    const slug: string = "slug_example"
    return expect(instance.retrieveAidCenter(slug, {})).resolves.toBe(null)
  })
  test("updateAidCenter", () => {
    const slug: string = "slug_example"
    const body: api.AidCenter = undefined
    return expect(instance.updateAidCenter(slug, body, {})).resolves.toBe(null)
  })
})

describe("ApiApi", () => {
  let instance: api.ApiApi
  beforeEach(function() {
    instance = new api.ApiApi(config)
  });

  test("listprivates", () => {
    return expect(instance.listprivates({})).resolves.toBe(null)
  })
  test("listpublics", () => {
    return expect(instance.listpublics({})).resolves.toBe(null)
  })
  test("listrestricteds", () => {
    return expect(instance.listrestricteds({})).resolves.toBe(null)
  })
})

