import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr';
import styles from '../styles/Home.module.css'

const fetcher = (input: RequestInfo, init?: RequestInit) => fetch(input, init).then(res => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR('http://localhost:8000/test/joladni-jo', fetcher);
  const { slug } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Jól adni jó</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Jól adni jó. Teszteljük a backend hívást: {slug} {error && '😱 😱 😱'}
        </h1>

        
      </main>

      <footer className={styles.footer}>
        ...
      </footer>
    </div>
  )
}

export default Home
