import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import getConfig from 'next/config';

const fetcher = (input: RequestInfo, init?: RequestInit) => fetch(input, init).then((res) => res.json());
const { publicRuntimeConfig } = getConfig();

interface HomeProps {
  slug: string;
  environmentName: string;
}

const getBackendBaseUrl = ({ ENVIRONMENT }: any) => {
  if (ENVIRONMENT === 'staging') {
    return 'https://api.staging.joladnijo.jmsz.hu';
  } else if (ENVIRONMENT === 'production') {
    return 'https://api.staging.joladnijo.jmsz.hu';
  } else return 'http://localhost:8000';
};

const Home: NextPage<HomeProps> = ({ slug, environmentName }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jól adni jó</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Jól adni jó. Teszteljük a backend hívást {environmentName} kornyezetben: {slug}
        </h1>
      </main>

      <footer className={styles.footer}>...</footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const backendApiBaseUrl = getBackendBaseUrl(process.env);

  const res = await fetch(`${backendApiBaseUrl}/test/joladni-jo`);
  const { slug } = await res.json();
  return { props: { slug, environmentName: process.env.ENVIRONMENT as string } };
};
